# Generated by Django 3.0.3 on 2020-10-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bryggelogg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bryggnr', models.IntegerField(blank=True, null=True)),
                ('navn', models.CharField(blank=True, max_length=264, null=True)),
                ('dato', models.DateField(blank=True, null=True)),
                ('og', models.FloatField(blank=True, null=True)),
                ('fg', models.FloatField(blank=True, null=True)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('effektivitet', models.FloatField(blank=True, null=True)),
                ('sluttvolum', models.FloatField(blank=True, null=True)),
                ('utbytte', models.FloatField(blank=True, null=True)),
                ('mesketemperatur', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('meskevann', models.FloatField(blank=True, null=True)),
                ('kokevolum', models.FloatField(blank=True, null=True)),
                ('etterfylling', models.FloatField(blank=True, null=True)),
                ('gjaer', models.CharField(blank=True, max_length=264, null=True)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('malt_1', models.CharField(blank=True, max_length=264)),
                ('m_mengde_1', models.FloatField(blank=True, null=True)),
                ('malt_2', models.CharField(blank=True, max_length=264)),
                ('m_mengde_2', models.FloatField(blank=True, null=True)),
                ('malt_3', models.CharField(blank=True, max_length=264)),
                ('m_mengde_3', models.FloatField(blank=True, null=True)),
                ('malt_4', models.CharField(blank=True, max_length=264)),
                ('m_mengde_4', models.FloatField(blank=True, null=True)),
                ('malt_5', models.CharField(blank=True, max_length=264)),
                ('m_mengde_5', models.FloatField(blank=True, null=True)),
                ('humle_1', models.CharField(blank=True, max_length=264)),
                ('h_mengde_1', models.FloatField(blank=True, null=True)),
                ('humle_2', models.CharField(blank=True, max_length=264)),
                ('h_mengde_2', models.FloatField(blank=True, null=True)),
                ('humle_3', models.CharField(blank=True, max_length=264)),
                ('h_mengde_3', models.FloatField(blank=True, null=True)),
                ('humle_4', models.CharField(blank=True, max_length=264)),
                ('h_mengde_4', models.FloatField(blank=True, null=True)),
                ('humle_5', models.CharField(blank=True, max_length=264)),
                ('h_mengde_5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('type', models.CharField(max_length=264)),
                ('date', models.DateField(blank=True, null=True)),
                ('og', models.FloatField(blank=True, null=True)),
                ('fg', models.FloatField(blank=True, null=True)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('ibu', models.FloatField(blank=True, default='', null=True)),
                ('efficiency', models.FloatField(blank=True, null=True)),
                ('batch_volume', models.FloatField(blank=True, null=True)),
                ('mash_time', models.IntegerField(blank=True, null=True)),
                ('boil_time', models.IntegerField(blank=True, null=True)),
                ('mash_temp', models.IntegerField(blank=True, null=True)),
                ('boil_volume', models.FloatField(blank=True, null=True)),
                ('fermenter_volume', models.FloatField(blank=True, null=True)),
                ('yeast', models.CharField(blank=True, max_length=264, null=True)),
                ('link', models.CharField(blank=True, max_length=264, null=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malt', models.CharField(max_length=264)),
                ('amount', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bryggelogg.Recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop', models.CharField(default='', max_length=264)),
                ('amount', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bryggelogg.Recipes')),
            ],
        ),
    ]
