# Generated by Django 3.0.3 on 2020-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bryggelogg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bryggnr', models.IntegerField()),
                ('navn', models.CharField(max_length=264)),
                ('dato', models.DateField()),
                ('og', models.FloatField()),
                ('fg', models.FloatField()),
                ('abv', models.FloatField()),
                ('effektivitet', models.FloatField()),
                ('sluttvolum', models.FloatField()),
                ('utbytte', models.FloatField()),
                ('mesketemperatur', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('meskevann', models.FloatField()),
                ('kokevolum', models.FloatField()),
                ('etterfylling', models.FloatField()),
                ('gjaer', models.CharField(max_length=264)),
                ('kommentar', models.TextField()),
                ('malt_1', models.FloatField()),
                ('m_mengde_1', models.FloatField()),
                ('malt_2', models.FloatField()),
                ('m_mengde_2', models.FloatField()),
                ('malt_3', models.FloatField()),
                ('m_mengde_3', models.FloatField()),
                ('malt_4', models.FloatField()),
                ('m_mengde_4', models.FloatField()),
                ('malt_5', models.FloatField()),
                ('m_mengde_5', models.FloatField()),
                ('humle_1', models.FloatField()),
                ('h_mengde_1', models.FloatField()),
                ('humle_2', models.FloatField()),
                ('h_mengde_2', models.FloatField()),
                ('humle_3', models.FloatField()),
                ('h_mengde_3', models.FloatField()),
                ('humle_4', models.FloatField()),
                ('h_mengde_4', models.FloatField()),
                ('humle_5', models.FloatField()),
                ('h_mengde_5', models.FloatField()),
            ],
        ),
    ]
