# Generated by Django 3.0.3 on 2020-10-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='boil_time',
            field=models.IntegerField(default=0),
        ),
    ]
