# Generated by Django 3.0.3 on 2020-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='og',
            field=models.FloatField(default=0.0),
        ),
    ]
