# Generated by Django 3.0.3 on 2020-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='bryggnr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='dato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='effektivitet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='etterfylling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='fg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='kokevolum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='meskevann',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
