# Generated by Django 3.0.3 on 2020-10-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0002_hop_boil_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop',
            name='boil_time',
            field=models.IntegerField(default=''),
        ),
    ]
