# Generated by Django 3.0.3 on 2020-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0003_auto_20200830_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='humle_1',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='humle_2',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='humle_3',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='humle_4',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='humle_5',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='malt_1',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='malt_2',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='malt_3',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='malt_4',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='malt_5',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
