# Generated by Django 3.0.3 on 2020-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0003_malt_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
