# Generated by Django 3.0.3 on 2020-08-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0004_auto_20200830_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='og',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='sluttvolum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
