# Generated by Django 3.0.3 on 2020-10-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0004_recipes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='batch_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='boil_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='bottle_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='fg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='mash_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='mash_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='og',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='refil_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='yeast',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
