# Generated by Django 3.0.3 on 2020-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0005_auto_20201003_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='link',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
