# Generated by Django 3.0.3 on 2020-08-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0006_auto_20200830_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='mesketemperatur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
