# Generated by Django 3.0.3 on 2020-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0007_auto_20200830_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='m_mengde_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
