# Generated by Django 3.0.3 on 2020-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bryggelogg', '0008_auto_20200830_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bryggelogg',
            name='h_mengde_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='h_mengde_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='h_mengde_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='h_mengde_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='h_mengde_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='m_mengde_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='m_mengde_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='m_mengde_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bryggelogg',
            name='m_mengde_5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
