from django.db import models

# Create your models here.
class Bryggelogg(models.Model):
    bryggnr = models.IntegerField(blank = True)
    navn = models.CharField(blank = True, max_length = 264)
    dato = models.DateField(blank = True)
    og = models.FloatField(blank = True, null = True)
    fg = models.FloatField(blank = True)
    abv = models.FloatField(blank = True)
    effektivitet = models.FloatField(blank = True)
    sluttvolum = models.FloatField(blank = True, null = True)
    utbytte = models.FloatField(blank = True, null = True)
    mesketemperatur = models.IntegerField(blank = True, null = True)
    rating = models.IntegerField(blank = True)
    meskevann = models.FloatField(blank = True)
    kokevolum = models.FloatField(blank = True)
    etterfylling = models.FloatField(blank = True)
    gjaer = models.CharField(blank = True, max_length = 264)
    kommentar = models.TextField(blank = True)
    malt_1 = models.CharField(blank = True, max_length = 264)
    m_mengde_1 = models.FloatField(blank = True, null = True)
    malt_2 = models.CharField(blank = True, max_length = 264)
    m_mengde_2 = models.FloatField(blank = True, null = True)
    malt_3 = models.CharField(blank = True, max_length = 264)
    m_mengde_3 = models.FloatField(blank = True, null = True)
    malt_4 = models.CharField(blank = True, max_length = 264)
    m_mengde_4 = models.FloatField(blank = True, null = True)
    malt_5 = models.CharField(blank = True, max_length = 264)
    m_mengde_5 = models.FloatField(blank = True, null = True)
    humle_1 = models.CharField(blank = True, max_length = 264)
    h_mengde_1 = models.FloatField(blank = True, null = True)
    humle_2 = models.CharField(blank = True, max_length = 264)
    h_mengde_2 = models.FloatField(blank = True, null = True)
    humle_3 = models.CharField(blank = True, max_length = 264)
    h_mengde_2 = models.FloatField(blank = True, null = True)
    humle_3 = models.CharField(blank = True, max_length = 264)
    h_mengde_3 = models.FloatField(blank = True, null = True)
    humle_4 = models.CharField(blank = True, max_length = 264)
    h_mengde_4 = models.FloatField(blank = True, null = True)
    humle_5 = models.CharField(blank = True, max_length = 264)
    h_mengde_5 = models.FloatField(blank = True, null = True)

    def __str__(self):
        return self.navn
